const CONFIG = {
  API_BASE: window.SELL_API_BASE || '/api',
  REGION: window.AWS_REGION || 'ap-south-1',
  COGNITO_DOMAIN: window.COGNITO_DOMAIN || '',
  COGNITO_CLIENT_ID: window.COGNITO_CLIENT_ID || '',
  COGNITO_REDIRECT_URI: window.COGNITO_REDIRECT_URI || window.location.origin + '/sell/new.html',
};
function authToken(){const p=new URLSearchParams(window.location.hash.slice(1)||window.location.search.slice(1));const t=p.get('id_token')||p.get('access_token')||localStorage.getItem('id_token');if(t)localStorage.setItem('id_token',t);return t;}
function login(){if(!CONFIG.COGNITO_DOMAIN||!CONFIG.COGNITO_CLIENT_ID){alert('Login not configured');return;}const u=`${CONFIG.COGNITO_DOMAIN}/login?client_id=${CONFIG.COGNITO_CLIENT_ID}&response_type=token&redirect_uri=${encodeURIComponent(CONFIG.COGNITO_REDIRECT_URI)}`;window.location.href=u;}
function logout(){localStorage.removeItem('id_token');alert('Logged out');window.location.reload();}
async function api(path,opt={}){const h=Object.assign({'Content-Type':'application/json'},opt.headers||{});const t=authToken();if(t)h['Authorization']=t;const r=await fetch(CONFIG.API_BASE+path,{...opt,headers:h});if(!r.ok)throw new Error(await r.text());return r.json();}
async function listListings(q={}){const p=new URLSearchParams(q).toString();return api('/sell/listings'+(p?'?'+p:''),{method:'GET',headers:{'Content-Type':'application/json'}});}
function cardHtml(it){const img=(it.images&&it.images[0])||'./media/placeholder.jpg';const badge=it.size||'Container';const loc=it.location||'';const price=it.price?`$${it.price}`:'';const vid=it.video||'';return `<article class="card">${vid?`<video controls preload="metadata" src="${vid}"></video>`:`<img src="${img}" alt="">`}<div class="content"><div class="badge">${badge}</div><h3>${it.title||'Untitled'}</h3><p>${loc} ${price?('• '+price):''}</p><p>${(it.description||'').slice(0,140)}...</p></div></article>`;}
async function renderGrid(){const g=document.getElementById('listingGrid');if(!g)return;try{const q={q:document.getElementById('q')?.value||'',size:document.getElementById('size')?.value||'',condition:document.getElementById('condition')?.value||'',location:document.getElementById('location')?.value||''};const data=await listListings(q);g.innerHTML=(data.items||[]).map(cardHtml).join('')||'<p>No listings yet.</p>';}catch(e){g.innerHTML='<p>Failed to load listings.</p>';console.error(e);}}
function bindFilters(){['q','size','condition','location'].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener('change',renderGrid);if(el&&el.tagName==='INPUT')el.addEventListener('input',e=>{clearTimeout(window.__qtimer);window.__qtimer=setTimeout(renderGrid,400);});});}
async function handleForm(){const f=document.getElementById('listingForm');if(!f)return;f.addEventListener('submit',async(e)=>{e.preventDefault();const t=authToken();if(!t){alert('Please login first');return;}const fd=new FormData(f);const payload={title:fd.get('title'),size:fd.get('size'),condition:fd.get('condition'),location:fd.get('location'),description:fd.get('description'),specs:fd.get('specs'),price:parseFloat(fd.get('price')||'0'),availabilityFrom:fd.get('availabilityFrom')||null,images:[],video:null};const images=f.querySelector('input[name="images"]').files;const video=f.querySelector('input[name="video"]').files[0];for(let i=0;i<Math.min(images.length,10);i++){const file=images[i];const {uploadUrl, publicUrl}=await api('/sell/presign',{method:'POST',body:JSON.stringify({filename:file.name,contentType:file.type})});await fetch(uploadUrl,{method:'PUT',body:file});payload.images.push(publicUrl);}if(video){const {uploadUrl, publicUrl}=await api('/sell/presign',{method:'POST',body:JSON.stringify({filename:video.name,contentType:video.type})});await fetch(uploadUrl,{method:'PUT',body:video});payload.video=publicUrl;}await api('/sell/listings',{method:'POST',body:JSON.stringify(payload)});alert('Listing published!');window.location.href='./index.html';});}
function initAuthButtons(){const t=authToken();const loginBtn=document.getElementById('loginBtn');const logoutBtn=document.getElementById('logoutBtn');if(loginBtn)loginBtn.onclick=login;if(logoutBtn)logoutBtn.onclick=logout;if(t){if(loginBtn)loginBtn.style.display='none';if(logoutBtn)logoutBtn.style.display='inline-block';}}
document.addEventListener('DOMContentLoaded',()=>{bindFilters();renderGrid();handleForm();initAuthButtons();});