AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ContainerBazar AI Chatbot (Python)

Globals:
  Function:
    Timeout: 15
    MemorySize: 1024
    Runtime: python3.11

Resources:
  ChatbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.lambda_handler
      Environment:
        Variables:
          OPENAI_API_KEY: 
      Events:
        ChatApi:
          Type: Api
          Properties:
            Path: /chat
            Method: post